config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "sints#index"
  

  resources :piets
  resources :sints
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/piet.rb
class Piet < ApplicationRecord
  belongs_to :sint

  validates :name, presence: true
  validates :name, uniqueness: true
validates :theme, presence: true
  validates :age, length: { maximum: 3 }, allow_blank: true
  validates :image_url, length: { maximum: 255 }, allow_blank: true


  def gender_to_s
    if self.gender == true
      "Male"
    else
      "Female"
    end
  end
end

app/models/sint.rb
class Sint < ApplicationRecord
  has_many :piets
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/piets_controller.rb
class PietsController < ApplicationController
  def index
    @piets = Piet.all
  end

  def show
    @piet = Piet.find(params[:id])
  end

  def new
    @piet = Piet.new
  end

  def create
    piet_params= params.require(:piet).permit( :name, :age, :gender, :theme, :image_url, :sint_id)
    @piet = Piet.new(piet_params)

      if @piet.save
        redirect_to @piet
      else
       render 'new'
     end
  end
end

app/controllers/sints_controller.rb
class SintsController < ApplicationController
  def index
  @sints= Sint.all
  end

  # show method for the index page
  def show
    @sint=Sint.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/piets_helper.rb
module PietsHelper
end

app/helpers/sints_helper.rb
module SintsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RentAPiet</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/piets/new.html.erb
<h1>New Piet</h1>

<p>Hi!</p>
<p> Want to join our organisation? Just fill in this form and you're on!</p>

<%= form_for @piet do |f| %>
  <ul>
    <% @piet.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
  <div class="form">  <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
<div class="form">
    <%= f.label :age %>
    <%= f.number_field :age %>
</div>
<div class="form">
    <%= f.label :gender %>
    <%= f.label :gender, "Male", :value => "true"  %>
    <%= f.radio_button :gender, true %>
    <%= f.label :gender, "Gender Female", :value => "false" %>
    <%= f.radio_button :gender, false %>
</div>
<div class="form">

<%= f.label :theme %>
    <%= f.text_field :theme %>
</div>
<div class="form">
    <%= f.label :sint %>
    <%= f.collection_select(:sint_id, Sint.all, :id, :name) %>
</div>
<div class="form">
    <%= f.label :image_url %>
    <%= f.text_field :image_url %>
  </div>
  <div class="form">
    <%= f.submit "Create" %>
</div>


<% end %>

<div>
<button> <%= link_to 'Home', sints_path %></button>
</div>

app/views/piets/show.html.erb
<body>
<h1>Piet</h1>


<h2> Hi, this is the Piet you selected</h2>
<div>
  <p><span>Name:</span><%= @piet.name %></p>
  <p><span>Age:</span><%= @piet.age %></p>
  <p><span>Gender:</span><%= @piet.gender_to_s %></p>
  <p><span>Theme:</span><%= @piet.theme %></p>
  <p><span>Team:</span><%= @piet.sint.name %></p>
  <p><%= image_tag @piet.image_url %></p>

</div>
<div>
<button> <%= link_to 'Home', sints_path %></button>
</div>
</body>

app/views/sints/index.html.erb


<body >

<div style="background:#8B0000 ;
border:1px solid #CCC;
border-radius: 25px;
width:100%;
margin:0px auto;
height:140px;">



<h1 >Rent a Piet</h1>
</div>

<div>
  <p >Welcome to Rent a Piet! We are THE Sinterklaas and Piet renting website in The Netherlands! Based on our active community of volunteers, we aim to rent an ideal package for every Dutch household. Call the phone number regarding your favourite team, and make an appointment right away!</p>
  <p >Click on your favourite Sinterklaas, and watch which great helpers are dedicated to this Holy man.</p>
  <p >Also, it would be <stron>Great</strong> if you would subcribe yourself as a Pieter volunteer! Click on the link on the bottom of the page.</p>
</div>

<div style="color:black;
font-size:28px;
font-weight: bold;
display: inline-block;
vertical-align: top;
padding: 1px;
margin: 10px">
<% @sints.each do |sint| %>
  
    <p><%= link_to sint.name, sint_path(sint.id) %></p>
  <p ><%= image_tag sint.image_url %></p></p>
</div>

<% end %>

<div>
  <p >Click HERE to subscribe as a volunteer Piet!</p>
  <%= link_to "[New Piet]", new_piet_path %>

</div>
</body>

app/views/sints/show.html.erb
<body>
<h1>

  Welcome to <%= @sint.name %>
</h1>

<p>
  <%= image_tag @sint.image_url %>

</p>

<h2>List of Piets</h2>

<div class="piet-container">

<% if @sint.piets.any? %>

    <% @sint.piets.each do |piet| %>
    <div class="piet-individual">
      <p><%= link_to "#{piet.name} - click for details", piet_path(piet.id)  %></p>
      <p><%= image_tag piet.image_url %></p>
    </div>
    <% end %>

<% else %>
  <p>This Sint doesn't have any Piet yet.</p>
<% end %>
/<div>

<button><%= link_to 'Home', sints_path %></button>
</body>